const advanceFilterData: advanceFIlterDataType = [
  {
    title: 'Connectivity',
    content: [
      { id: 1, name: 'Test' },
      { id: 2, name: 'Test' },
      { id: 3, name: 'Test' },
      { id: 4, name: 'Test' },
      { id: 5, name: 'Test' },
      { id: 6, name: 'Test' },
      { id: 7, name: 'Test' },
      { id: 8, name: 'Test' },
      { id: 9, name: 'Test' },
      { id: 10, name: 'Test' },
      { id: 11, name: 'Test' },
      { id: 12, name: 'Test' },
      { id: 13, name: 'Test' },
      { id: 14, name: 'Test' },
    ],
  },
  {
    title: 'Furnishing',
    content: [
      { id: 15, name: 'Group' },
      { id: 16, name: 'Group' },
      { id: 17, name: 'Group' },
      { id: 18, name: 'Group' },
      { id: 19, name: 'Group' },
      { id: 20, name: 'Group' },
      { id: 21, name: 'Group' },
      { id: 22, name: 'Group' },
    ],
  },
  {
    title: 'Leisure  Amenities',
    content: [
      { id: 23, name: 'Other' },
      { id: 24, name: 'Other' },
      { id: 25, name: 'Other' },
      { id: 26, name: 'Other' },
      { id: 27, name: 'Other' },
      { id: 28, name: 'Other' },
      { id: 29, name: 'Other' },
      { id: 30, name: 'Other' },
      { id: 31, name: 'Other' },
      { id: 32, name: 'Other' },
      { id: 33, name: 'Other' },
      { id: 34, name: 'Other' },
      { id: 35, name: 'Other' },
      { id: 36, name: 'Other' },
    ],
  },
  {
    title: 'Connectivity',
    content: [
      { id: 37, name: 'Teasing' },
      { id: 38, name: 'Teasing' },
      { id: 39, name: 'Teasing' },
      { id: 40, name: 'Teasing' },
      { id: 41, name: 'Teasing' },
      { id: 42, name: 'Teasing' },
      { id: 43, name: 'Teasing' },
      { id: 44, name: 'Teasing' },
      { id: 45, name: 'Teasing' },
      { id: 46, name: 'Teasing' },
      { id: 47, name: 'Teasing' },
      { id: 48, name: 'Teasing' },
      { id: 49, name: 'Teasing' },
    ],
  },
];

export default advanceFilterData;
