<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table(config('tables.question_options'))->insert([
            [
                'question_id' => 1,
                'instruction' => NULL,
                'value' => 'age_18_19',
                'label_for_app' => 'Age: 18-29',
                'label_for_web' => '18-29',
                'min_val' => 18,
                'max_val' => 29,
                'image' => 'assets/images/questions_image/18-19.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 1,
                'instruction' => NULL,
                'value' => 'age_30_39',
                'label_for_app' => 'Age: 30-39',
                'label_for_web' => '30-39',
                'min_val' => 30,
                'max_val' => 39,
                'image' => 'assets/images/questions_image/30.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 1,
                'instruction' => NULL,
                'label_for_app' => 'Age: 40-49',
                'label_for_web' => '40-49',
                'min_val' => 40,
                'max_val' => 49,
                'value' => 'age_40_49',
                'image' => 'assets/images/questions_image/40.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 1,
                'instruction' => NULL,
                'label_for_app' => 'Age: 50+',
                'label_for_web' => '50+',
                'min_val' => 50,
                'max_val' => 50,
                'value' => 'age_50',
                'image' => 'assets/images/questions_image/50.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 2,
                'label_for_app' => 'Muscle Gain',
                'label_for_web' => 'Muscle Gain',
                'min_val' => 50,
                'max_val' => 50,
                'instruction' => 'and get rid of fat',
                'value' => 'muscle_gain',
                'image' => 'assets/images/questions_image/muscle_gain.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 2,
                'label_for_app' => 'Weight Loss',
                'label_for_web' => 'Weight Loss',
                'min_val' => null,
                'max_val' => null,
                'instruction' => 'without loosing muscle',
                'value' => 'weight_loss',
                'image' => 'assets/images/questions_image/w-l.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 2,
                'label_for_app' => 'Get Shredded',
                'label_for_web' => 'Get Shredded',
                'min_val' => null,
                'max_val' => null,
                'instruction' => 'and stay in shape',
                'value' => 'get_shredded',
                'image' => 'assets/images/questions_image/gs.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],


            [
                'question_id' => 3,
                'label_for_app' => 'Slim',
                'label_for_web' => 'Slim',
                'min_val' => 50,
                'max_val' => 50,
                'instruction' => NULL,
                'value' => 'slim',
                'image' => 'assets/images/questions_image/slim.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 3,
                'label_for_app' => 'Average',
                'label_for_web' => 'Average',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'average',
                'image' => 'assets/images/questions_image/average.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 3,
                'label_for_app' => 'Heavy',
                'label_for_web' => 'Heavy',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'heavy',
                'image' => 'assets/images/questions_image/heavy.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 3,
                'label_for_app' => 'Overweight',
                'label_for_web' => 'Overweight',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'overweight',
                'image' => 'assets/images/questions_image/overweight.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],

            [
                'question_id' => 4,
                'label_for_app' => 'Back',
                'label_for_web' => 'Back',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'back',
                'image' => 'assets/images/questions_image/back.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 4,
                'label_for_app' => 'Pecs',
                'label_for_web' => 'Pecs',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'pecs',
                'image' => 'assets/images/questions_image/pecs.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 4,
                'label_for_app' => 'Arms',
                'label_for_web' => 'Arms',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'arms',
                'image' => 'assets/images/questions_image/arms.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 4,
                'label_for_app' => 'Belly',
                'label_for_web' => 'Belly',
                'min_val' => 50,
                'max_val' => 50,
                'instruction' => NULL,
                'value' => 'belly',
                'image' => 'assets/images/questions_image/belly.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 4,
                'label_for_app' => 'Legs',
                'label_for_web' => 'Legs',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'legs',
                'image' => 'assets/images/questions_image/legs.png',
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 6,
                'label_for_app' => 'Less than 12',
                'label_for_web' => 'Less than 12',
                'min_val' => 0,
                'max_val' => 12,
                'instruction' => NULL,
                'value' => '12_and_above',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 6,
                'label_for_app' => '12-20',
                'label_for_web' => '12-20',
                'min_val' => 12,
                'max_val' => 20,
                'instruction' => NULL,
                'value' => 'lt_12',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 6,
                'label_for_app' => 'More than 21',
                'label_for_web' => 'More than 21',
                'min_val' => 21,
                'max_val' => 100,
                'instruction' => NULL,
                'value' => '12_and_above',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 6,
                'label_for_app' => 'I dont know',
                'label_for_web' => 'I dont know',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'do_not_know',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 5,
                'label_for_app' => 'Beginner',
                'label_for_web' => 'Beginner',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'beginner',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],
            [
                'question_id' => 5,
                'label_for_app' => 'Intermediate',
                'label_for_web' => 'Intermediate',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'intermediate',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],

            [
                'question_id' => 5,
                'label_for_app' => 'Advance',
                'label_for_web' => 'Advance',
                'min_val' => null,
                'max_val' => null,
                'instruction' => NULL,
                'value' => 'advance',
                'image' => NULL,
                'created_at' => '2025-04-23 16:14:59',
                'updated_at' => '2025-04-23 16:14:59',
            ],

            [
                'question_id' => 7,
                'label_for_app' => 'Fewer than 5 hours',
                'label_for_web' => 'Fewer than 5 hours',
                'instruction' => null,
                'value' => 'fewer_than_5_hours',
                'min_val' => 0,
                'max_val' => 5,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 7,
                'label_for_app' => 'Between 5 and 6 hours',
                'label_for_web' => 'Between 5 and 6 hours',
                'instruction' => null,
                'value' => 'gt_6',
                'min_val' => 5,
                'max_val' => 6,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 7,
                'label_for_app' => 'Between 7 and 8 hours',
                'label_for_web' => 'Between 7 and 8 hours',
                'instruction' => null,
                'value' => 'gt_6',
                'min_val' => 7,
                'max_val' => 8,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 7,
                'label_for_app' => 'Over 8 hours',
                'label_for_web' => 'Over 8 hours',
                'instruction' => null,
                'value' => 'gt_6',
                'min_val' => 9,
                'max_val' => 24,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            // [
            //     'question_id' => 8,
            //     'label_for_app' => 'Fewer than 5 hours',
            //     'label_for_web' => 'Fewer than 5 hours',
            //     'instruction' => null,
            //     'value' => 'lt_5_hours',
            //     'min_val' => 0,
            //     'max_val' => 5,
            //     'image' => null,
            //     'created_at' => '2025-04-23 11:44:59',
            //     'updated_at' => '2025-04-23 11:44:59',
            // ],
            // [
            //     'question_id' => 8,
            //     'label_for_app' => 'Between 5 and 6 hours',
            //     'label_for_web' => 'Between 5 and 6 hours',
            //     'instruction' => null,
            //     'value' => '5_6_hours',
            //     'min_val' => 5,
            //     'max_val' => 6,
            //     'image' => null,
            //     'created_at' => '2025-04-23 11:44:59',
            //     'updated_at' => '2025-04-23 11:44:59',
            // ],
            // [
            //     'question_id' => 8,
            //     'label_for_app' => 'Between 7 and 8 hours',
            //     'label_for_web' => 'Between 7 and 8 hours',
            //     'instruction' => null,
            //     'value' => '7_8_hours',
            //     'min_val' => 7,
            //     'max_val' => 8,
            //     'image' => null,
            //     'created_at' => '2025-04-23 11:44:59',
            //     'updated_at' => '2025-04-23 11:44:59',
            // ],
            // [
            //     'question_id' => 8,
            //     'label_for_app' => 'Over 8 hours',
            //     'label_for_web' => 'Over 8 hours',
            //     'instruction' => null,
            //     'value' => 'gt_8_hours',
            //     'min_val' => 8,
            //     'max_val' => 8,
            //     'image' => null,
            //     'created_at' => '2025-04-23 11:44:59',
            //     'updated_at' => '2025-04-23 11:44:59',
            // ],


            [
                'question_id' => 8,
                'label_for_app' => 'Only coffee or tea',
                'label_for_web' => 'Only coffee or tea',
                'instruction' => null,
                'value' => 'coffee_tea_only',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 8,
                'label_for_app' => 'Less than 2 glasses',
                'label_for_web' => 'Less than 2 glasses',
                'instruction' => null,
                'value' => 'lt_2_glasses',
                'min_val' => 0,
                'max_val' => 2,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 8,
                'label_for_app' => '2-6 glasses',
                'label_for_web' => '2-6 glasses',
                'instruction' => null,
                'value' => '2_6_glasses',
                'min_val' => 3,
                'max_val' => 6,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 8,
                'label_for_app' => '7-10 glasses',
                'label_for_web' => '7-10 glasses',
                'instruction' => null,
                'value' => '7_10_glasses',
                'min_val' => 7,
                'max_val' => 10,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 9,
                'label_for_app' => 'Veg',
                'label_for_web' => 'Veg',
                'instruction' => 'Achieve a healthy weight faster than others',
                'value' => 'veg',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 9,
                'label_for_app' => 'Non-veg',
                'label_for_web' => 'Non-Veg',
                'instruction' => null,
                'value' => 'non_veg',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 9,
                'label_for_app' => 'Vegan',
                'label_for_web' => 'Vegan',
                'instruction' => 'Excludes all animal products',
                'value' => 'vegan',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 9,
                'label_for_app' => 'Keto',
                'label_for_web' => 'Keto',
                'instruction' => 'Low-carb, high-fat',
                'value' => 'keto',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],


            [
                'question_id' => 10,
                'label_for_app' => 'Highly organized',
                'label_for_web' => 'Highly organized',
                'instruction' => null,
                'value' => 'highly_organized',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 10,
                'label_for_app' => 'Moderately organized',
                'label_for_web' => 'Moderately organized',
                'instruction' => null,
                'value' => 'moderately_organized',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 10,
                'label_for_app' => 'Need assistance',
                'label_for_web' => 'Need assistance',
                'instruction' => null,
                'value' => 'need_assistance',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],
            [
                'question_id' => 10,
                'label_for_app' => 'Completely disorganized',
                'label_for_web' => 'Completely disorganized',
                'instruction' => null,
                'value' => 'disorganized',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 11:44:59',
                'updated_at' => '2025-04-23 11:44:59',
            ],

            [
                'question_id' => 11,
                'label_for_app' => '',
                'label_for_web' => 'Upto 5 feet',
                'instruction' => null,
                'value' => 'Upto 5 feet',
                'min_val' => 0,
                'max_val' => 5,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 11,
                'label_for_app' => '',
                'label_for_web' => '5.1- 6 feet',
                'instruction' => null,
                'value' => '5.1- 6 feet',
                'min_val' => 5,
                'max_val' => 6,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 11,
                'label_for_app' => '',
                'label_for_web' => '6+ feet',
                'instruction' => null,
                'value' => '6+ feet',
                'min_val' => 6,
                'max_val' => 6,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '0-44',
                'instruction' => null,
                'value' => '0-44',
                'min_val' => 0,
                'max_val' => 44,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '45-54',
                'instruction' => null,
                'value' => '45-54',
                'min_val' => 45,
                'max_val' => 54,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '55-64',
                'instruction' => null,
                'value' => '55-64',
                'min_val' => 55,
                'max_val' => 64,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '65-74',
                'instruction' => null,
                'value' => '65-74',
                'min_val' => 65,
                'max_val' => 74,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '75-94',
                'instruction' => null,
                'value' => '75-94',
                'min_val' => 75,
                'max_val' => 94,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 12,
                'label_for_app' => '',
                'label_for_web' => '95+',
                'instruction' => null,
                'value' => '95+',
                'min_val' => 95,
                'max_val' => 95,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],


            [
                'question_id' => 13,
                'label_for_app' => '',
                'label_for_web' => '0-44',
                'instruction' => null,
                'value' => '0-44',
                'min_val' => 0,
                'max_val' => 44,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 13,
                'label_for_app' => '',
                'label_for_web' => '45-54',
                'instruction' => null,
                'value' => '45-54',
                'min_val' => 45,
                'max_val' => 54,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 13,
                'label_for_app' => '',
                'label_for_web' => '55-64',
                'instruction' => null,
                'value' => '55-64',
                'min_val' => 55,
                'max_val' => 64,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 13,
                'label_for_app' => '',
                'label_for_web' => '65-74',
                'instruction' => null,
                'value' => '65-74',
                'min_val' => 65,
                'max_val' => 74,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 13,
                'label_for_app' => '',
                'label_for_web' => '75-94',
                'instruction' => null,
                'value' => '75-94',
                'min_val' => 75,
                'max_val' => 94,
                'image' => null,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'question_id' => 15,
                'label_for_app' => 'Home',
                'label_for_web' => 'Home',
                'instruction' => null,
                'value' => 'home',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/home.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 15,
                'label_for_app' => 'Gym',
                'label_for_web' => 'Gym',
                'instruction' => null,
                'value' => 'gym',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/gym.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
              [
                'question_id' => 15,
                'label_for_app' => 'Both',
                'label_for_web' => 'Both',
                'instruction' => null,
                'value' => 'both',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/gym.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Vacation',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'vacation',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/vacation.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Sporting Event',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'sporting_event',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/sporting_event.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Important Date',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'important_date',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/important_date.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Adventure Trip',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'adventure_trip',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/adventure_trip.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Birthday',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'birthday',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/birthday.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Beach Trip',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'beach_trip',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/beach_trip.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Reunion',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'reunion',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/reunion.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 17,
                'label_for_app' => 'Family Occasion',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'family_occasion',
                'min_val' => null,
                'max_val' => null,
                'image' => 'assets/images/questions_image/family_occasion.png',
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 18,
                'label_for_app' => 'In a months',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'in_a_months',
                'min_val' => 0,
                'max_val' => 1,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 18,
                'label_for_app' => 'In less than 3 months',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'less_3m',
                'min_val' => 1,
                'max_val' => 3,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 18,
                'label_for_app' => 'In less than 6 months',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'less_6m',
                'min_val' => 3,
                'max_val' => 6,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 18,
                'label_for_app' => 'In more than 6 months',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'above_6m',
                'min_val' => 6,
                'max_val' => 6,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 20,
                'label_for_app' => 'Yes, I will do my first workout tomorrow',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'workout_tomorrow',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 20,
                'label_for_app' => 'Yes! I will do my first workout today!',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'workout_tomorrow',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ],
            [
                'question_id' => 20,
                'label_for_app' => 'I am not ready to make the commitment',
                'label_for_web' => null,
                'instruction' => null,
                'value' => 'no_commitment',
                'min_val' => null,
                'max_val' => null,
                'image' => null,
                'created_at' => '2025-04-23 10:29:31',
                'updated_at' => '2025-04-23 10:29:31',
            ]
        ]);
    }
}
