import './globals.css';
import '@mantine/core/styles.css';
import 'react-toastify/dist/ReactToastify.css';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ColorSchemeScript, Container, MantineProvider, createTheme, mantineHtmlProps, rem } from "@mantine/core";
import { ThemeProvider } from "./context/ThemeContext";
import ReduxProvider from "@/context/ReduxProvider";
import { FormProvider } from "@/context/FormContext";
import { ToastContainer } from 'react-toastify';
import SingleTabGuard from './components/guards/SingleTabGuard';
import localFont from 'next/font/local';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next Klub-business App",
  description: "Generated by create next app",
};

const CONTAINER_SIZES: Record<string, number> = {
  xxs: 300,
  xs: 400,
  sm: 500,
  md: 600,
  lg: 700,
  xl: 800,
  xxl: 900,
};

const theme = createTheme({
  fontFamily: 'var(--font-satoshi), sans-serif',
  colors: {
  },

  shadows: {
    md: '1px 1px 3px rgba(0, 0, 0, .25)',
    xl: '5px 5px 3px rgba(0, 0, 0, .25)',
    sm: '',
  },

  headings: {
    fontFamily: 'var(--font-satoshi), sans-serif',
    sizes: {
      h1: { fontSize: '16px' },
    },
  },
  components: {

  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en"
        {...mantineHtmlProps}
      >
        <head>
          <ColorSchemeScript />
          <link href="https://unpkg.com/tailwindcss@1.9.6/dist/tailwind.min.css" rel="stylesheet"></link>
        </head>
        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} > */}
        <body className={`antialiased`} >
          <MantineProvider theme={theme} defaultColorScheme={`light`} cssVariablesSelector={`html`} deduplicateCssVariables={false} classNamesPrefix={`kb`} withStaticClasses={false} withGlobalClasses={true} env={`test`} >
            <SingleTabGuard />
            <ToastContainer position="top-right" autoClose={3000} />
            <ThemeProvider>
              <ReduxProvider>
                <FormProvider>
                  <Container size="xxs" bg="var(--mantine-color-transparent)" px={0} fluid>
                    {children}
                  </Container>
                </FormProvider>
              </ReduxProvider>
            </ThemeProvider>
          </MantineProvider>
        </body>
      </html>
    </>
  );
}
