<?php
namespace App\Interfaces;

interface RepositoryInterface
{
	public function getAllCompanies();
	public function newCompanies();
	public function getCompaniesById($id);
	public function deleteCompanies($id);
	public function createCompanies(array $details);
	public function createAllHeadTransaction(array $details);
	public function updateCompanies($id, array $details);
	public function getAllModel($model);
	public function getModelById($model, $id);
	public function deleteModel($model, $id);
	public function createModel($model, array $details);
	public function updateModel($model, $id, array $details);
	public function getAllTdsDeductionSetting();
	public function getTdsDeductionSettingById($id);
	public function deleteTdsDeductionSetting($id);
	public function createTdsDeductionSetting(array $details);
	public function updateTdsDeductionSetting($id, array $details);
	public function getUserById($id);
	public function getAllAccountHeads();
	public function getAllPlans();
	public function getAllRelations();
	public function getAllSystemDefaultSettings();
	public function getNewSystemDefaultSettings();
	public function createSystemDefaultSettings(array $details);
	public function updateSystemDefaultSettings($id, array $details);
	public function getPlansById($id);
	public function getAllPlanTenures();
	public function createPlanTenures(array $details);
	public function getAllCarder();
	public function getAllBranchCash();
	public function getAllCommissionLoanDetails();
	public function createCommissionLoanDetails(array $commissionLoanDetails);
	public function getAllCompanyBranch();
	public function createCompanyBranch(array $details);
	public function insertCompanyBranch(array $details);
	public function updateCompanyBranch($id, array $details);
	public function getCompanyBranchById($id);
	public function getNewCompanyBranch();
	public function deleteCompanyBranch($id);
	public function getAllSamraddhBank();
	public function getAllSamraddhBankAccounts();
	public function getAllBranch();
	public function getAllMember();
	public function getAllMemberCompany();
	public function getAllSavingAccount();
	public function getAllSavingAccountWithMember($id);
	public function CreateMemberinvestmentsnominees(array $details);
	public function CreateMemberinvestments(array $details);
	public function CreateMemberCompany(array $details);
	public function CreateSavingAccount(array $details);
	public function getBankBalance($entryDate, $companyId, $bankId, $accountId, $endDate);
	public function getAllMemberinvestments();
	public function getAllDaybook();
	public function getAllCommissionDetail();
	public function createCommissionDetail(array $details);
	public function insertAllHeadTransaction(array $details);
	public function getAllMemberNominee();
	public function getAllGrouploans();
	public function getAllMemberloans();
	public function getCorrectionRequestsById($id);
	public function getSavingAccountTranscationById($id);
	public function getDaybookById($id);
	public function getAllTransactionType();
	public function getTransactionTypeById($id);
	public function getAllCommissionLeaserMonthly();
	public function getAllSavingAccountTranscation();
	public function getSavingAccountById($id);
	public function getMemberinvestmentsById($id);
	public function getHeadTransactionById($id);
	public function getBranchDaybookById($id);
	public function getAllBranchDaybook();
	public function getSamraddhBankDaybookById($id);
	public function getAllSamraddhBankDaybook();
	public function getAllReceivedCheque();
	public function getReceivedChequeById($id);
	public function createCorrectionLog(array $details);
	public function getAllBranchCurrentBalance();
	public function getAllFundTransfer();
	public function getBranchById($id);
	public function getHeadSettingById($id);
	public function createHeadSetting(array $data);
	public function getAllHeadSetting();
	public function getAllGstTransaction();
	public function getAllStates();
	public function getGstSettingById($id);
	public function getAllGstSetting();
	public function createGstSetting(array $data);
	public function createFiles(array $data);
	public function getDutiesTaxesPayableById($id);
	public function getAllDutiesTaxesPayable();
	public function getAllTdsTransfer();
	public function createTdsTransfer(array $data);
	public function getTdsTransferById($id);
	public function createDutiesTaxesPayable(array $data);
	public function createDutiesTaxesSettingLog(array $data);
	public function getAllDutiesTaxesSettingLog();
	public function getDutiesTaxesSettingLogByTypeId($id);
	public function getDutiesTaxesSettingLogById($id);
	public function updateHeadSetting($data,$id);
	public function getAllSamraddhCheque();
	public function getSamraddhChequeByChequeNo($chequeNo);
	public function getSamraddhChequeById($id);
	public function getMemberById($id);
	public function getChequeLogById($id);
	public function updateSamraddhCheque($data,$id);
}
